### ISSUE TITLE
PA:REVIEW Photos index page, upload form and show page 

### ISSUE THREAD

**Issue by roniRamon** [roniRamon/snapics#10]
- [x] Logged in Users can upload photos
- [x] Users can view list of Photos
- [x] Users can press on a photo to view the photo in a larger size

**Comment by wongshington** [comment]
- [x]  should be able to click out of the photo upload modal from anywhere off the screen, not just the X
- [x] the "Photo Title" and "Photo Description" text should have just a little bit of space from the border of those text fields
- [x] make the "upload" button on the form a little bigger
- [x] make the errors text size a little bigger as well
- [x] space out the photos a little bit more if possible

**Comment by wongshington** [comment]
everything looks really good, these are just some small spacing fixes mostly

**Comment by roniRamon** [comment]
i made all the changes.
