### ISSUE TITLE
PA:REVIEW Albums 

### ISSUE THREAD

**Issue by roniRamon** [roniRamon/snapics#11]
- [x] Logged in Users can create an album
- [x] Logged in Users can add photos to an album
- [x] Users can view other users photo albums

**Comment by wongshington** [comment]
- [x] when a user uploads a photo be sure to clear the form afterwards much like a session form
- [x] add a specific error message for if there isn't an image uploaded, "Img url can't be blank" doesn't really explain what the issue is

**Comment by roniRamon** [comment]
fixed issues
